# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Deploy Private Key
        env:
          CENTOS_KEY: ${{ secrets.CENTOS_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$CENTOS_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host cdn.hackshen.com\nStrictHostKeyChecking no\nHostName cdn.hackshen.com\nUser root\nIdentityFile ~/.ssh/id_rsa\n" >> ~/.ssh/config
      - name: install & build
        run: |
          npm install
          npm run build
      - name: push file
        run: |
          rsync -rv --delete -e 'ssh -o stricthostkeychecking=no' build/ root@cdn.hackshen.com:/root/work/
